### ISSUE TITLE
Build breaking when used with latest Nuxt version

### ISSUE THREAD

**Issue by alexgrozav** [harlan-zw/nuxt-simple-sitemap#113]
### Describe the bug

```
[error] [nitro] RollupError: "useAppConfig" is not exported by "virtual:#imports", imported by "node_modules/nuxt-site-config/dist/runtime/nitro/middleware/init.mjs".
--
10:51:13.163 |  
10:51:13.163 |  
10:51:13.163 | 1: import { defineEventHandler, updateSiteConfig, useAppConfig, useNitroOrigin, useRuntimeConfig } from "#imports";
10:51:13.163 | ^
10:51:13.163 | 2: export default defineEventHandler((e) => {
10:51:13.163 | 3:   if (!e.context.siteConfig) {
10:51:13.165 | [error] "useAppConfig" is not exported by "virtual:#imports", imported by "node_modules/nuxt-site-config/dist/runtime/nitro/middleware/init.mjs".
10:51:13.166 | at error (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
10:51:13.166 | at Module.error (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:13604:16)
10:51:13.166 | at Module.traceVariable (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:14029:29)
10:51:13.166 | at ModuleScope.findVariable (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:12547:39)
10:51:13.166 | at ReturnValueScope.findVariable (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
10:51:13.166 | at ChildScope.findVariable (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
10:51:13.166 | at TrackingScope.findVariable (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
10:51:13.166 | at BlockScope.findVariable (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
10:51:13.166 | at Identifier.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:8267:40)
10:51:13.166 | at CallExpression.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
10:51:13.166 | at CallExpression.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:9833:15)
10:51:13.166 | at VariableDeclarator.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
10:51:13.166 | at VariableDeclaration.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
10:51:13.167 | at BlockStatement.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
10:51:13.167 | at IfStatement.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
10:51:13.167 | at BlockStatement.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
10:51:13.167 | at ArrowFunctionExpression.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
10:51:13.167 | at CallExpression.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
10:51:13.167 | at CallExpression.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:9833:15)
10:51:13.167 | at ExportDefaultDeclaration.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
10:51:13.167 | at Program.bind (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
10:51:13.167 | at Module.bindReferences (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:13600:18)
10:51:13.167 | at Graph.sortModules (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:25665:20)
10:51:13.167 | at Graph.build (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:25549:14)
10:51:13.167 | at async node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:26510:13
10:51:13.167 | at async catchUnfinishedHookActions (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:25722:16)
10:51:13.167 | at async rollupInternal (node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:26505:5)
10:51:13.167 | at async _build (node_modules/nitropack/dist/shared/nitro.36074cb2.mjs:2168:18)
10:51:13.167 | at async prerender (node_modules/nitropack/dist/shared/nitro.36074cb2.mjs:3958:3)
10:51:13.167 | at async node_modules/nuxt/dist/index.mjs:2641:7
10:51:13.167 | at async build (node_modules/nuxt/dist/index.mjs:3794:5)
10:51:13.167 | at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:59:5)
10:51:13.168 | at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
10:51:13.290 | Error: Command "npm run build && npm run generate" exited with 1
```

### Reproduction

https://github.com/inkline/inkline.io/pull/12

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.2.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      modules, experimental, app, css, components, content, devServer, i18n, inkline, image, vite, imports, pwa, runtimeConfig
- Runtime Modules:  @nuxt/content@2.7.2, @nuxt/image-edge@1.0.0-28008586.381b906, @inkline/plugin/nuxt@1.5.2, @nuxtjs/i18n@8.0.0-rc.2, @vite-pwa/nuxt@0.1.0, @unocss/nuxt@0.54.1, nuxt-icon@0.4.2, nuxt-simple-sitemap@3.1.5
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hey @alexgrozav, sorry for the delay, have been pretty swamped.

Thanks for the issue and your work on Inkline, it's a cool project! The issue is that you've locked the `nitropack` version.

```json
    "overrides": {
        "nitropack": "2.2.1"
    }
```

This version of nitropack doesn't have the `useAppConfig` available that Nuxt Simple Sitemap needs.

I've sent a PR which resolves & updates the deps https://github.com/inkline/inkline.io/pull/13

**Comment by alexgrozav** [comment]
Thank you so much for the update and the kind words! 🙏 Hope you'll give Inkline a try sometime. Sorry for the trouble!
