### ISSUE TITLE
Error after upgrading from v2.7.0 to v3.3.4

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-simple-sitemap#142]
### Describe the bug

I get the following error when trying to access http://localhost:3000/sitemap.xml
When accessing the page, I get redirected to http://localhost:3000/sitemap_index.xml. Error 500
```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'href')
  at <anonymous> (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:131:71)  
  at Array.map (<anonymous>)  
  at normaliseEntry (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:129:50)  
  at Array.map (<anonymous>)  
  at normaliseEntries (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:152:32)  
  at normaliseSitemapData (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:171:10)  
  at buildSitemapIndex (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/builder/sitemap-index.mjs:21:32)  
  at <anonymous> (./node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap_index.xml.mjs:20:16)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'href')
  at <anonymous> (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:131:71)  
  at Array.map (<anonymous>)  
  at normaliseEntry (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:129:50)  
  at Array.map (<anonymous>)  
  at normaliseEntries (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:152:32)  
  at normaliseSitemapData (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/entries/normalise.mjs:171:10)  
  at buildSitemapIndex (./node_modules/nuxt-simple-sitemap/dist/runtime/sitemap/builder/sitemap-index.mjs:21:32)  
  at <anonymous> (./node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap_index.xml.mjs:20:16)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
```

`nuxt-simple-sitemap` is simply added in the list of `modules`, with no specific configuration (no `sitemap` section in `nuxt.config.ts`). Site URL is define as an environment variable: `NUXT_PUBLIC_SITE_URL`

My workaround is to revert to v2.7.0

Would you be able to point me to ways to debug?

### Reproduction

Difficult to provide a repro, it's my production site ...

### System / Nuxt Info

```Shell
------------------------------
- Operating System: `Linux`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.7.3`
- Nitro Version:    `2.6.3`
- Package Manager:  `npm@9.8.1`
- Builder:          `vite`
- User Config:      `extends`, `appConfig`, `css`, `postcss`, `build`, `modules`, `runtimeConfig`, `auth`, `content`, `experimental`, `i18n`, `image`, `nitro`, `pwa`, `routeRules`, `robots`, `security`, `vite`
- Runtime Modules:  `@sidebase/nuxt-auth@0.5.0`, `@nuxtjs/i18n@8.0.0-rc.4`, `@pinia/nuxt@0.4.11`, `@vueuse/nuxt@10.4.1`, `@nuxt/image-edge@1.0.0-rc.1-28135297.08462d1`, `@nuxt/content@2.7.0`, `nuxt-simple-sitemap@3.3.4`, `nuxt-simple-robots@3.1.5`, `nuxt-og-image@2.0.28`, `@kevinmarrec/nuxt-pwa@0.17.0`, `nuxt-security@0.14.4`
- Build Modules:    `-`
------------------------------
```

**Comment by harlan-zw** [comment]
Hey @tmlmt, not sure what's going on here but it seems like you have a nulled alternative entry.

It should handle this case a bit better in 3.3.5, so let me know if you stilll have issues.

**Comment by tmlmt** [comment]
Thanks @harlan-zw ! No 500-error anymore, and I do get a landing sitemap pointing to 3 different sitemaps for the 3 locales that I have, but then the list is messed up (some pages are not indexed, route rules are not taken into account, etc.).
So this issue is closed, but I'll investigate with your latest doc and will revert (probably on discord first) if I'm in doubt.
