### ISSUE TITLE
Dynamic routes not generated

### ISSUE THREAD

**Issue by Envaya** [harlan-zw/nuxt-simple-sitemap#177]
Hi all

### Describe the bug
Maybe I'm missing something, but I still can't get any dynamic sitemap entries to show up when running my built project.  Meanwhile` nuxt dev` works without issues. Old bug report: https://github.com/harlan-zw/nuxt-simple-sitemap/issues/150

This is my `/api/__sitemap__/urls.ts`:

```
export default defineSitemapEventHandler(async () => {
  return [
    {
      loc: '/de/test',
    },
    {
      loc: '/test',
    },
  ];
});

```
In the nuxt config I specified the source:
```
sitemap: {
    sources: ['/api/__sitemap__/urls'],
  },

```
When running in dev:
![Screenshot 2023-12-04 at 11 28 20](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/18561427/24b67eca-bd34-4347-86a1-63536680c676)

When running build:
![Screenshot 2023-12-04 at 11 35 55](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/18561427/2268a112-21d4-4479-9c32-245b2383a45e)

`[nuxt-simple-sitemap] Failed to fetch source. {
  url: '/api/__sitemap__/urls',
      error: FetchError: [GET] "/api/__sitemap__/urls": 401
  at async $fetch2 (.../apps/website/.output/server/chunks/nitro/node-server.mjs:2668:15)
  at async fetchDataSource (.../apps/website/.output/server/chunks/nitro/node-server.mjs:6322:18)
  at async Promise.all (index 0)
  at async resolveSitemapSources (.../apps/website/.output/server/chunks/nitro/node-server.mjs:6374:11)
  at async buildSitemap (.../apps/website/.output/server/chunks/nitro/node-server.mjs:6803:25)
  at async createSitemap (.../apps/website/.output/server/chunks/nitro/node-server.mjs:6876:17)
  at async Object.handler (.../apps/website/.output/server/chunks/nitro/node-server.mjs:2199:19)
  at async Server.toNodeHandle (.../apps/website/.output/server/chunks/nitro/node-server.mjs:2388:7)
}
`

### System / Nuxt Info

  System:
    OS: macOS 11.2
    CPU: (8) arm64 Apple M1
    Memory: 318.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      css, modules, basicAuth, i18n, devServerHandlers, build, runtimeConfig, components, image, vite, robots
- Runtime Modules:  nuxt-icon@0.4.1, @nuxt/image@1.0.0-rc.3, @nuxtjs/tailwindcss@6.7.2, @nuxtjs/i18n@8.0.0-rc.5, @nuxt/devtools@1.0.4, @storyblok/nuxt@5.7.9, (), nuxt-simple-robots@3.1.9, @kgierke/nuxt-basic-auth@1.3.1
- Build Modules:

**Comment by hellencheetah** [comment]
> Seems like something is throwing a 401 when accessing the route, maybe there is some auth on your API routes? Nuxt doesn't have this inbuilt.
> 
> You could try a `server/routes/__sitemap.ts` and using the `/__sitemap` path to fetch them.

I got the same error. I did what you'd written and I still get this error.

**Comment by hellencheetah** [comment]
I got the error as well
"[nuxt-simple-sitemap] Failed to fetch source. {
  url: 'server/routes/__sitemap.ts',
  error: FetchError: [GET] "server/routes/__sitemap.ts": <no response> Failed to parse URL from server/routes/__sitemap.ts
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async $fetchRaw2 (file:///C:/Projects/prodamus-nuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)
      ... 5 lines matching cause stack trace ...
      at createSitemap (C:\Projects\prodamus-nuxt\node_modules\nuxt-simple-sitemap\dist\runtime\sitemap\nitro.mjs:26:17)
      at async Object.handler (file:///C:/Projects/prodamus-nuxt/node_modules/h3/dist/index.mjs:1675:19)
      at async Server.toNodeHandle (file:///C:/Projects/prodamus-nuxt/node_modules/h3/dist/index.mjs:1885:7) {
    [cause]: TypeError: Failed to parse URL from server/routes/__sitemap.ts
        at Object.fetch (node:internal/deps/undici/undici:11457:11)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async $fetchRaw2 (file:///C:/Projects/prodamus-nuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:219:26)
        at async $fetchRaw2 (file:///C:/Projects/prodamus-nuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)
        at async $fetch2 (file:///C:/Projects/prodamus-nuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
        ... 4 lines matching cause stack trace ...
        at createSitemap (C:\Projects\prodamus-nuxt\node_modules\nuxt-simple-sitemap\dist\runtime\sitemap\nitro.mjs:26:17) {
      [cause]: [TypeError]
    }
  }
"
```
import { defineSitemapEventHandler } from '#imports';

export default defineSitemapEventHandler(async () => {

    return [
        '/hahaha'
    ];
});

```

**Comment by harlan-zw** [comment]
A TypeError is being thrown, maybe because you have `async` and are not returning a promise.

**Comment by harlan-zw** [comment]
Haven't heard back from OP so going to close for now.

**Comment by yuuzora** [comment]
Hello, sorry for reopening, I'm getting the same problem, but it also doesn't works for nuxt dev.
Using `@nuxtjs/sitemap: 5.1.4`

It's the same Type Error, except I've tried with async and without, tried to use: `server/routes/__sitemap.ts` as you said before, but I still get the error.

<img width="1098" alt="image" src="https://github.com/nuxt-modules/sitemap/assets/16171988/14103663-d3a0-447c-9f86-bf8b49594803">
However the url does work correctly when called by anything else than the sitemap source: 
<img width="891" alt="image" src="https://github.com/nuxt-modules/sitemap/assets/16171988/602fcb59-4f13-41a1-9db5-720b0aafbea7">

Also, when running dev mode, if I do any change server side and Nitro is rebuilt, it will be called again and then load the url correctly:
<img width="1258" alt="image" src="https://github.com/nuxt-modules/sitemap/assets/16171988/52f6f953-61f7-43fa-afc5-867944f84381">

Config looks like this: `sitemap: {
        autoI18n: false,
        include: [],
        sitemaps: {
            'fr-FR': {
                sources: [
                    '/api/__sitemap__/fr',
                  ]
            },
            'en-US': {
                sources: [
                    '/api/__sitemap__/en',
                  ]
            },
            'es-ES': {
                sources: [
                    '/api/__sitemap__/es',
                  ]
            } 
        },
        hostname: process.env.BASE_URL,
    },`

Any idea?

**Comment by yxw007** [comment]
I have the same problem，it seems to work well when I change it to the following. I hope it was helpful

![Image](https://github.com/user-attachments/assets/94a43136-76d7-49bd-9ced-74c7be3bc0e2)
