### ISSUE TITLE
Cannot start Nuxt: Int.Segmenter is not a constructor

### ISSUE THREAD

**Issue by toddpadwick** [harlan-zw/nuxt-simple-sitemap#75]
### Describe the bug

Getting this error after adding the sitemap module:
```
Cannot start nuxt:  Intl.Segmenter is not a constructor                                                                                                                             15:26:25

  at stringWidth (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/shared/consola.a16d1131.mjs:458:37)
  at FancyReporter.formatLogObj (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/shared/consola.a16d1131.mjs:579:41)
  at FancyReporter.log (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/shared/consola.06ad8a64.mjs:51:23)
  at Consola._log (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/core.mjs:381:16)
  at resolveLog (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/core.mjs:349:14)
  at Consola._logFn (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/core.mjs:377:5)
  at Consola.warn (node_modules/nuxt-simple-sitemap/node_modules/consola/dist/core.mjs:306:19)
  at normalizedModule (node_modules/nuxt-simple-sitemap/node_modules/@nuxt/kit/dist/index.mjs:2125:16)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:435:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2253:7)
  at async load (node_modules/nuxt/node_modules/nuxi/dist/chunks/dev.mjs:6802:9)
  at async Object.invoke (node_modules/nuxt/node_modules/nuxi/dist/chunks/dev.mjs:6863:5)
  at async _main (node_modules/nuxt/node_modules/nuxi/dist/cli.mjs:51:20)
```

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `app`, `modules`, `hooks`, `sanity`, `runtimeConfig`, `target`, `image`, `css`, `vite`, `alias`, `nitro`
- Runtime Modules:  `@nuxtjs/sanity@1.6.0`, `nuxt-jsonld@2.0.7`, `@pinia/nuxt@0.4.7`, `@nuxt/image-edge@1.0.0-27952794.567c688`, `@vueuse/nuxt@9.13.0`, `nuxt-simple-sitemap@2.7.0`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Hey @toddpadwick, this looks like an issue with consola using Node 16 internals.

You should upgrade your node version, the official recommendation is `Node.js - [v16.10.0](https://nodejs.org/en/) or newer`

See https://nuxt.com/docs/getting-started/installation

**Comment by toddpadwick** [comment]
Ah thats fantastic. thank you @harlan-zw I keep forgetting to check my nvm version. silly mistake.
