### ISSUE TITLE
Error 500 on production mode via /sitemap.xml

### ISSUE THREAD

**Issue by wokalek** [harlan-zw/nuxt-simple-sitemap#85]
### Describe the bug

[nuxt] [request error] [unhandled] [500] fetch failed (http://localhost/__sitemap__/routes.json)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async $fetchRaw2 (./.output/server/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)  
  at async $fetch2 (./.output/server/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)  
  at async Promise.all (index 1)  
  at async resolveAsyncSitemapData (./.output/server/chunks/nitro/node-server.mjs:2324:3)  
  at async buildSitemap (./.output/server/chunks/nitro/node-server.mjs:2488:22)  
  at async ./.output/server/chunks/nitro/node-server.mjs:2622:15  
  at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1284:19)  
  at async Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1359:7)
[Vue Router warn]: No match found for location with path "/sitemap.xml"

### System / Nuxt Info

```Shell
- Operating System: Linux
- Node Version:     v20.3.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      telemetry, srcDir, app, modules, runtimeConfig, vite, css, postcss, colorMode, device, image, content, pwa, robots, site, sitemap, schemaOrg
- Runtime Modules:  @nuxtjs/robots@3.0.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/fontaine@0.4.0, @nuxtjs/device@3.1.0, @nuxt/content@2.7.0, @nuxt/image@1.0.0-rc.1, @vueuse/nuxt@10.2.1, @vite-pwa/nuxt@0.1.0, nuxt-typed-router@3.2.4, nuxt-svgo@3.2.0, nuxt-simple-sitemap@3.0.5, nuxt-schema-org@2.2.0, nuxt-lodash@2.5.0
- Build Modules:    -
```

**Comment by wokalek** [comment]
Running in docker.

**Comment by wokalek** [comment]
Seems like it's not docker problem, I expose 3000 port properly. 

I can access my api sitemap generation:

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/23037847/76b3831c-2f02-4a0b-80ba-df0400c26302)

But on `sitemap.xml` still have 500 error.

**Comment by wokalek** [comment]
So, I tried to reproduce this bug on playground in this repo, and what I got: 

```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'sitemapName')
  at ./.playground/.output/server/chunks/nitro/node-server.mjs:1394:45  
  at async Promise.all (index 1)  
  at async resolveAsyncSitemapData (./.playground/.output/server/chunks/nitro/node-server.mjs:1435:3)  
  at async buildSitemap (./.playground/.output/server/chunks/nitro/node-server.mjs:1601:22)  
  at async ./.playground/.output/server/chunks/nitro/node-server.mjs:1775:15  
  at async Object.handler (./.playground/.output/server/node_modules/h3/dist/index.mjs:1284:19)  
  at async Server.toNodeHandle (./.playground/.output/server/node_modules/h3/dist/index.mjs:1359:7)
```

With this settings: 

```
sitemap: {
  dynamicUrlsApiEndpoint: '/api/_sitemap-urls',
},
```

**Comment by harlan-zw** [comment]
Hey, sorry I have a fix hopefully coming for this, give me ~20 min

**Comment by harlan-zw** [comment]
Please try 3.0.6 :pray:
