### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] input.match is not a function

### ISSUE THREAD

**Issue by 7Koston** [harlan-zw/nuxt-simple-sitemap#89]
### Describe the bug

Building `nuxt build --modern=server` throws thing below:
Everything was working fine on `nuxt-simple-sitemap` version `2.7.0`.

 ```
 ERROR  [nuxt] [request error] [unhandled] [500] input.match is not a function                      
  at parsePath (/C:/Development/dimer-nuxt/node_modules/ufo/dist/index.mjs:441:58)
  at parseURL (/C:/Development/dimer-nuxt/node_modules/ufo/dist/index.mjs:424:60)
  at fixSlashes (/C:/Development/dimer-nuxt/.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:2587:18)
  at resolveSitePath (/C:/Development/dimer-nuxt/.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:2584:58)
  at Object.relativeBaseUrlResolver (/C:/Development/dimer-nuxt/.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:2633:12)
  at buildSitemap (/C:/Development/dimer-nuxt/.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:3057:18)
  at runNextTicks (node:internal/process/task_queues:60:5)
  at listOnTimeout (node:internal/timers:538:9)
  at process.processTimers (node:internal/timers:512:7)
  at async /C:/Development/dimer-nuxt/.nuxt/prerender/chunks/nitro/nitro-prerenderer.mjs:3141:15
  at async Object.handler (/C:/Development/dimer-nuxt/node_modules/h3/dist/index.mjs:1284:19)
  at async toNodeHandle (/C:/Development/dimer-nuxt/node_modules/h3/dist/index.mjs:1359:7)
  at async ufetch (/C:/Development/dimer-nuxt/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (/C:/Development/dimer-nuxt/node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:98:17)
  at async processRoute (/C:/Development/dimer-nuxt/node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:156:20)
  at async Promise.all (index 0)
  at async runParallel (/C:/Development/dimer-nuxt/node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:218:3)
  at async prerender (/C:/Development/dimer-nuxt/node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:175:3)
  at async /C:/Development/dimer-nuxt/node_modules/nuxt/dist/index.mjs:2634:7
  at async build (/C:/Development/dimer-nuxt/node_modules/nuxt/dist/index.mjs:3785:5)
  at async Object.invoke (/C:/Development/dimer-nuxt/node_modules/nuxi/dist/chunks/build.mjs:59:5)
  at async _main (/C:/Development/dimer-nuxt/node_modules/nuxi/dist/cli.mjs:49:20)
  ```
  
Prerender is enabled. `robots.txt` generates just fine, `sitemap.xml` throws thing above.
Same thing for `sitemap.xml` even with prerender disabled.

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.0
- Builder:          vite
- User Config:      modules, typescript, routeRules, css, googleFonts, gtag, facebook, i18n, dayjs, lazyLoad, nitro, robots, sitemap, site, runtimeConfig
- Runtime Modules:  @nuxtjs/google-fonts@3.0.1, @nuxtjs/i18n@8.0.0-beta.13, nuxt-gtag@0.5.7, nuxt-svgo@3.3.0, nuxt-lazy-load@3.0.4, nuxt-simple-robots@3.0.2, nuxt-simple-sitemap@3.0.8, nuxt3-meta-pixel@1.0.9, dayjs-nuxt@1.1.2
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Please use 3.0.9
